### ISSUE TITLE
How to play HiRes DSF files on a HiRes USB DAC with SqueezeBox and Squeezelite installed?

### ISSUE THREAD

**Issue by eric-joris** [pssc/ha-addon-squeezelite#10]
I have a HiRes USB DAC connected to an Intel NUC with SqueezeBox and Squeezelite installed. All works fine. The DAC is capable to play at 384K sample rate and 32Bit wide. However, when I play HiRes files (DSF), the output om my DAC is limited to 44.1K. 

Is there a way to increase the sample rate and bit size when I play HiRes files through LMS and Squeezelite?

**Comment by pssc** [comment]
@eric-joris again a expect your best configure squeezelite to use the DAC directly as some of the software layers may be getting in the way this might also be best directed towards forums and users that use squeezelite for such things. Maybe then a recipe could be added to the docs. I know in the logitech forums people are doing what you describe with squeezelite and LMS

**Comment by eric-joris** [comment]
@pssc Thanks, I try the Logitech forums.
