### ISSUE TITLE
Title appears in quotes

### ISSUE THREAD

**Issue by brjhaverkamp** [pssc/ha-addon-squeezelite#11]
Hi Phill,

Thanks for this add-on! 
I just installed it, and hope to make great use of it in my workshop.
One thing I notice. In the configuration I set the Name to Workshop. (Without any quotes)
In my squeezer app on my phone the player showed up immediately, but as 'Workshop'  (with the single quotes)

Can you take a look at this?

Regards,

Bert

**Comment by pssc** [comment]
Best to set the name in LMS rather than the addon it avoids these issues

**Comment by marcohamersma** [comment]
Not everyone uses the LMS or can get the official apps running. I mostly used it as a speaker with with Music Assistant, for example. The addon IMO seems the most straight-forward place for this to be for these usecases.

**Comment by brjhaverkamp** [comment]
Hi pssc, thanks for asigning this bug. And thanks for suggesting the workaround. Still, I agree with Marco that I would prefer to have this fixed in the add-on. Feels more clean to keep the settings there. I have several clients/players. And for all, I set the name on the device itself.

**Comment by brjhaverkamp** [comment]
Thanks for this! Fixed.
