### ISSUE TITLE
4 instances needed

### ISSUE THREAD

**Issue by klodeckl** [pssc/ha-addon-squeezelite#13]
Hi, thanks for the great addon! I would need totally 4 instances of squeezelitte. I found one clone addon, so I could run two instances. How can I run 4 instances? Thank you for your help!

**Comment by pssc** [comment]
I have upped number of instances to 4 [aa3a68d](https://github.com/pssc/ha-addon-squeezelite/commit/aa3a68d628e5baef087bc854be0e3c35d233d79f) enjoy.

**Comment by klodeckl** [comment]
Perfect, thank you! :)
