### ISSUE TITLE
[Feature Request] Possibility to create multiple instances

### ISSUE THREAD

**Issue by 7weazel7** [pssc/ha-addon-squeezelite#17]
It would be nice if you could manage multiple audio devices/sound cards via the addon. I am currently still using a Docker container for this.

services:
  squeezelite-essenzimmer-kueche:
    image: giof71/squeezelite:latest
    container_name: squeezelite-essenzimmer-kueche
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
    environment:
      - SQUEEZELITE_AUDIO_DEVICE=hw:CARD=Device,DEV=0
      - SQUEEZELITE_NAME=Esszimmer/Küche
      - SQUEEZELITE_SERVER_PORT=XXX.XXX.XXX.XXX
      - SQUEEZELITE_MAC_ADDRESS=00:00:00:00:00:01

  squeezelite-ankleide:
    image: giof71/squeezelite:latest
    container_name: squeezelite-ankleide
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
    environment:
      - SQUEEZELITE_AUDIO_DEVICE=hw:CARD=PCH,DEV=0
      - SQUEEZELITE_NAME=Ankleide
      - SQUEEZELITE_SERVER_PORT=XXX.XXX.XXX.XXX
      - SQUEEZELITE_MAC_ADDRESS=00:00:00:00:00:02

**Comment by pssc** [comment]
Hi @7weazel7 multiples instance are available in the addon repo currently supporting up to 4 instances at present.
