### ISSUE TITLE
Installation issue under HAOS14.0 on Proxmox

### ISSUE THREAD

**Issue by Pedason82** [pssc/ha-addon-squeezelite#18]
Hey Guys, 

im trying to pass music from MA to my local usb smsl DAC with Squeezelite for quiet some hours.
The usb DAC is connected to my local machine running Proxmox with HAOS14.
Usb is passed though to HAOS and everything is looking promissing.(DAC is shown up in HA)

Have to mention im still pretty new to HA and for some reasons i cant install squeezelite
always returning: 

"The command '/bin/bash -o pipefail -c cd /src && if [ ! -r squeezelite/Makefile ]; then git clone https://github.com/ralph-irving/squeezelite && cd squeezelite && git checkout ${SL_COMMIT};fi' returned a non-zero code: 128"

I am grateful for every advice
Adrian

**Comment by FLeXO21** [comment]
I had the same issue, this is the problem:

Cloning into 'squeezelite'...
fatal: reference is not a tree: 0e85ddfd79337cdc30b7d29922b1d790600bb6b4
 ---> Removed intermediate container a5a68fe605d4

What you can do is temporarly add the Addon locally in /addons
Then edit the Dockerfile and remove ` && git checkout ${SL_COMMIT}` from line 44

Or you can update the SL_COMMIT variable from line 18 to the lastest version `ARG SL_COMMIT=279ac086053239323f5c4df965342e3be5d10671`

Then you can install the addon locally.

**Comment by Pedason82** [comment]
Thank you for your reply

Actually i havnt tried that aproach
Since im using Proxmox i went with a different solution by setting up a new Lxc running Squeezelite, following this guide for the client(LXC) 

https://alshowto.com/add-multi-room-to-home-assistant/

passing everything sound related to the container, your config(/etc/pve/lxc/"xxx".conf) 
should look something like this 

arch: amd64
cores: 1
dev1: /dev/snd/controlC0
dev10: /dev/snd/pcmC1D8p
dev11: /dev/snd/pcmC1D9p
dev12: /dev/snd/seq
dev13: /dev/snd/timer
dev2: /dev/snd/controlC1
dev3: /dev/snd/hwC1D0
dev4: /dev/snd/hwC1D2
dev5: /dev/snd/pcmC0D0p
dev6: /dev/snd/pcmC1D0c
dev7: /dev/snd/pcmC1D0p
dev8: /dev/snd/pcmC1D3p
dev9: /dev/snd/pcmC1D7p
features: nesting=1
hostname: Squeeze
memory: 512
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.178.1,hwaddr=BC:24:11:3B:B4:A0,ip=192.168.178.5/24,type=veth
ostype: debian
rootfs: local-lvm:vm-103-disk-0,size=4G
swap: 512
unprivileged: 1

working fine 
not sure if i should close the issue, leaving it open for now ;-)

**Comment by pssc** [comment]
Thanks all, will push out a fixed release shortly
