### ISSUE TITLE
Login attempt or request with invalid authentication

### ISSUE THREAD

**Issue by plexkiki** [pssc/ha-addon-squeezelite#2]
Just moved from TrueNAS Home Assistant Core to Supervised Home Assistant with the Addon store. Tried installing LMS via Home Assistant and it worked the first time while I set up Spotty and Material skin. But now I can't get it to work at all. Every restart throws up the same error - even tried reinstalling from fresh and still nothing!

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:125
Integration: HTTP ([documentation](https://www.home-assistant.io/integrations/http), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+http%22))
First occurred: 13:04:10 (4 occurrences)
Last logged: 13:16:30
Login attempt or request with invalid authentication from [ipv6 home assistant/lms IP]

I assume I've just done something silly, but can't figure out what!

**Comment by pssc** [comment]
@plexkiki would need to see the start up logs, did you delete /config/lms when you reinstalled if not there will be state...

This is the squeezelite issue tracker so if you would like more support please log it against ha-addon-lms
