### ISSUE TITLE
run multiple copies

### ISSUE THREAD

**Issue by Sky-Jumper** [pssc/ha-addon-squeezelite#3]
Is it possible to add the ability to run multiple copies of the player?
It would be convenient to organize a multiroom with LMS.
I had a crash and installed two repositories and, accordingly, 2 players
I connected 2 usb sound cards and they worked each with their own player.
I tried to add another one, but HA does not give, writes that it is already installed.

**Comment by pssc** [comment]
@Sky-Jumper I will have a think I could clone the add on x times with a different slug and name, or alter the addon to support multiple instances how many do you need? option one is quick and dirty and option two is probably the way to do it but will take more care.

**Comment by Sky-Jumper** [comment]
I plan 5 zones, I am a supporter of elegant solutions, but if it is difficult to make the second option, then the first one will also work. Thanks.

**Comment by pssc** [comment]
@Sky-Jumper how technical are you? can you pull the next repo down locally (hit clone) and test squeezeplay1 works?

**Comment by Sky-Jumper** [comment]
I think I can

**Comment by pssc** [comment]
@Sky-Jumper I have done some local testing try again now

**Comment by Sky-Jumper** [comment]
I overestimated my strength, I couldn't download locally.
Couldn't figure out github.

P.S. I don't speak English, I use a translator.

**Comment by pssc** [comment]
@Sky-Jumper no worries.

in terminal addon
```
cd /addons/
git clone https://github.com/pssc/ha-addon-squeezelite.git -b next
```
goto addon page and select ... check for updates.
install Squeezelite clone 1.

Tell me what happens.

**Comment by Sky-Jumper** [comment]
Hi! It turned out to install, LMS saw them, but I killed HA in the heat of experiments, I'm busy at job now, I'll continue testing in a week.

**Comment by pssc** [comment]
@Sky-Jumper any progress?

**Comment by huseyinozsut** [comment]
Hi, I came from Homeassistant forum. I need two zones. Both will use usb sound cards. My technical ability is mediocre. :D But I am very dedicated and patient. :D

**Comment by pssc** [comment]
@huseyinozsut if you can pull down the next branch it has a 2nd player enabled in the repo

in terminal addon
```
cd /addons/
git clone https://github.com/pssc/ha-addon-squeezelite.git -b next
```
goto addon page and select ... check for updates. wait for a few mins.
install Squeezelite clone 1 configure sound output

Tell me what happens.

**Comment by pssc** [comment]
Anybody have anything to report

**Comment by huseyinozsut** [comment]
I am sorry, I wasn't available due to the help needed in Earthquake in the eastern Turkey region. I am going to test it tomorrow and report you back. Thank you for your affords.

**Comment by pssc** [comment]
I now test with 2 copies
