### ISSUE TITLE
LMS settings: 401:  unauthorized 

### ISSUE THREAD

**Issue by eric-joris** [pssc/ha-addon-squeezelite#7]
I just installed the LMS add-on version 8.3.1.58. In the browser (Https) all seems to work fine. I can get to the settings and help screens. In the companion app  however, I get the error: "401: unauthorised" when I try to access help or settings. 

Version: 2023.12.1
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2

Any help is very much appreciated.

**Comment by pssc** [comment]
Are you having issues with LMS or squeeze lite? As the is the squeeze lite add on issue tracker?

**Comment by eric-joris** [comment]
Is an Lms problem. Sorry wrong tracker.

**Comment by pssc** [comment]
@eric-joris please feel free to rise the issue in https://github.com/pssc/ha-addon-lms/issues instead
