### ISSUE TITLE
Installation on non-supervised HA? Is it possible?

### ISSUE THREAD

**Issue by oywino** [pssc/ha-addon-squeezelite#8]
Hi, Please explain how to install this "Add-on" for those of us **not** running HA-OS or HA-Supervised

**Comment by pssc** [comment]
Sorry I don't run or test on unsupported platforms for HA as my time is limited.

**Comment by oywino** [comment]
> Sorry I don't run or test on unsupported platforms for HA as my time is limited.

Sorry, but I don't understand your reply.
Running HA Core (non-Supervised) is definitely supported as an official installation method by the HA Dev Team:
https://www.home-assistant.io/installation/#advanced-installation-methods

If you were willing to release the code necessary to install it as a custom integration, I could do the testing for you.

**Comment by pssc** [comment]
Using addons are not supported outside of supervised and HAOS.  There is no code for a custom integration, all the code is released it the github repo, outside of the squeezelite code available elsewhere.

**Comment by oywino** [comment]
Aha, now I understand what you meant by "unsupported". Please excuse my ignorance.
But isn't there anything I can say (or do) to persuade you to spend a little bit of extra time to put together the code package needed to manually copy everything into a custom folder and run it from there?
It would make me (and I think many, many others) very happy to be able to have HA as a working LMS client.
Please?

**Comment by pssc** [comment]
@oywino technically this is not feasible it not python squeezelite is its own independent programme

**Comment by oywino** [comment]
> technically this is not feasible it not python squeezelite is its own independent programme
Well, if you say so 😶

Allow me to ask another question, also related to the Add-On install:
On the install page for this Add-On, it says:
![image](https://github.com/pssc/ha-addon-squeezelite/assets/18447119/b5dcadfc-c620-4249-8b51-bb91a3c12b1a)

What does "direct hardware access of the sound hardware" mean?
There is no sound hardware in my NUC where HA runs, but when I log into HA i.e. from my mobile phone using the companion App, the phone has "sound hardware", or if I log into HA from a Windows PC using the Chrome Browser, then the client PC has "Sound Hardware".  Is this what is meant by "sound hardware", or is it so that the HA server itself must have sound hardware" for this Add-on to work?  (which means it will play alone by itself sitting in a closet in my basement?) 😄 

And why does it present itself with an extra clone in the Add-On store?
![image](https://github.com/pssc/ha-addon-squeezelite/assets/18447119/c03c954b-b408-4926-9b91-7df4bca73bb3)
